import type { RatingItem } from '../types';
import { getLocalizedHkbuCanteenLabel } from '../data/hkbuCanteenTranslations';

const RATING_META_TRANSLATIONS: Record<'tc' | 'sc' | 'en', Record<string, string>> = {
  tc: {
    'Academy of Film': '電影學院',
    'Academy of Chinese, History, Religion and Philosophy': '中國語言、歷史、宗教及哲學學院',
    'Academy of Global China Studies': '全球中國研究學院',
    'Academy of Geography, Sociology and International Studies': '地理、社會學及國際研究學院',
    'Academy of Language and Culture': '語言及文化學院',
    'Academy of Music': '音樂學院',
    'Academy of Visual Arts': '視覺藝術院',
    'Academy of Wellness and Human Development': '身心健康及全人發展學院',
    'Asian Energy Studies Centre': '亞洲能源研究中心',
    'Centre for Applied Ethics': '應用倫理學中心',
    'Centre for Business Analytics and the Digital Economy': '商業分析與數字經濟中心',
    'Centre for China Urban and Regional Studies': '中國城市與區域研究中心',
    'Centre for Chinese Cultural Heritage': '中華文化遺產中心',
    'Centre for Chinese Herbal Medicine Drug Development Limited': '中藥新藥開發有限公司',
    'Centre for Corporate Governance and Financial Policy': '公司管治與金融政策研究中心',
    'Centre for Exercise Science and Medicine': '運動科學與醫學中心',
    'Centre for Family Office Management': '家族辦公室管理中心',
    'Centre for Health Informatics': '健康資訊學中心',
    'Centre for Health and Exercise Science Research': '健康與運動科學研究中心',
    'Centre for Human Resources Strategy and Development': '人力資源策略與發展中心',
    'Centre for Media and Communication Research': '媒體與傳播研究中心',
    'Centre for Nonlinear Studies': '非線性研究中心',
    'Centre for Quantitative Systems Biology': '定量系統生物學中心',
    'Centre for Sino-Christian Studies': '中華基督宗教研究中心',
    'Centre for Sustainable Development Studies': '可持續發展研究中心',
    'Centre for Translation': '翻譯中心',
    'Chinese Medicine - Clinical Division': '中醫臨床部',
    'Chinese Medicine - Division of Continuing and Professional Education': '中醫持續及專業教育部',
    'Chinese Medicine - Teaching and Research Division': '中醫教研部',
    'Chinese Medicine - Technology Development Division': '中醫技術發展部',
    'Chinese Medicine Hospital': '中醫醫院',
    'Comparative Governance and Policy Research Centre': '比較治理與政策研究中心',
    'Croucher Institute for Environmental Sciences': '裘槎環境科學研究所',
    'David C Lam Institute for East-West Studies': '林思齊東西學術交流研究所',
    'Department of Accountancy, Economics and Finance': '會計、經濟及金融學系',
    'Department of Biology': '生物系',
    'Department of Biomedical Sciences': '生物醫學系',
    'Department of Chemistry': '化學系',
    'Department of Chinese Language and Literature': '中文系',
    'Department of Communication Studies': '傳理學系',
    'Department of Computer Science': '計算機科學系',
    'Department of Education Studies': '教育學系',
    'Department of English Language and Literature': '英語語言文學系',
    'Department of Geography': '地理系',
    'Department of Government and International Studies': '政府與國際研究系',
    'Department of History': '歷史系',
    'Department of Humanities and Creative Writing': '人文及創作系',
    'Department of Interactive Media': '互動媒體系',
    'Department of Journalism': '新聞系',
    'Department of Management': '管理學系',
    'Department of Management, Marketing and Information Systems': '管理、市場及資訊系統學系',
    'Department of Marketing': '市場學系',
    'Department of Mathematics': '數學系',
    'Department of Music': '音樂系',
    'Department of Physics': '物理系',
    'Department of Psychology': '心理學系',
    'Department of Religion and Philosophy': '宗教及哲學系',
    'Department of Social Work': '社會工作系',
    'Department of Sociology': '社會學系',
    'Department of Sport, Physical Education and Health': '體育、運動及健康學系',
    'Department of Translation, Interpreting and Intercultural Studies': '翻譯、傳譯及跨文化研究系',
    'Division of Transdisciplinary Undergraduate Programmes': '跨學科本科課程部',
    'Digital Futures and Humanities': '數字未來與人文學',
    'Digital Humanities': '數碼人文學',
    'Dr. Stephen Hui Research Centre for Physical Recreation and Wellness': '許士芬博士體育康樂與健康研究中心',
    'Entrepreneurship and Innovation Centre': '創業及創新中心',
    'European Studies Programme': '歐洲研究課程',
    'Faculty of Arts and Social Sciences': '文學院及社會科學院',
    'Faculty of Arts and Social Sciences (CHRP)': '文學院及社會科學院（中華相關課程）',
    'Faculty of Arts and Social Sciences (LAC)': '文學院及社會科學院（語言與文化課程）',
    'Faculty of Interdisciplinary Research': '跨學科研究學院',
    'Faculty of Science': '理學院',
    'Faculty of Social Sciences': '社會科學院',
    'General Education': '通識教育',
    'General Education Office': '通識教育處',
    'HKBU Motion Capture and Visualization Laboratory': '浸大動作捕捉與可視化實驗室',
    'HKBU-RCEES Joint Institute of Environmental Sciences': '浸大—北師港浸大環境科學聯合研究院',
    'Ho Sin Hang Campus': '善衡校園',
    'Hong Kong Baptist University': '香港浸會大學',
    'Hong Kong Traditional Chinese Medicine Phenome Research Centre': '香港中醫藥表型研究中心',
    'High Performance Cluster Computing Centre': '高性能集群計算中心',
    'Institute of Transdisciplinary Studies (Undergraduate)': '跨學科本科課程學院',
    'Institute of Advanced Materials': '先進材料研究所',
    'Institute of Computational and Theoretical Studies': '計算與理論研究所',
    'Institute of Precision Medicine and Innovative Drug Discovery': '精準醫學與創新藥物研發研究所',
    'Kai Tak Campus': '啟德校園',
    'Language Centre': '語言中心',
    'Library': '圖書館',
    'Life Course Development Research Institute': '生命歷程發展研究所',
    'Life Science Imaging Centre': '生命科學成像中心',
    'Modern History Research Centre': '近代史研究中心',
    'Mr. Simon Suen and Mrs. Mary Suen Sino-Humanitas Institute': '孫少文伉儷人文中國研究所',
    'Office of the Dean of Arts and Social Sciences': '文學及社會科學學院院長辦公室',
    'Office of the Dean of Business': '工商管理學院院長辦公室',
    'Office of the Dean of Chinese Medicine': '中醫藥學院院長辦公室',
    'Office of the Dean of Communication': '傳理學院院長辦公室',
    'Office of the Dean of Creative Arts': '創意藝術學院院長辦公室',
    'Office of the Dean of Science': '理學院院長辦公室',
    'Office of the President and Vice-Chancellor': '校長兼副校監辦公室',
    'Office of the Provost': '教務長辦公室',
    'Office of the Vice-President (Administration) and Secretary': '副校長（行政）兼秘書長辦公室',
    'Office of the Vice-President (Research and Development)': '副校長（研究及拓展）辦公室',
    'Office of the Vice-President (Teaching and Learning)': '副校長（教與學）辦公室',
    'Peking University-HKBU Joint Research Institute for Applied Mathematics': '北京大學—浸會大學應用數學聯合研究所',
    'Research Centre for Herb Polysaccharides and Intestinal Immunology': '中藥多糖與腸道免疫研究中心',
    'Research Centre for Standardization of Chinese Medicines': '中藥標準化研究中心',
    'School of Business': '工商管理學院',
    'School of Chinese Medicine': '中醫藥學院',
    'School of Communication': '傳理學院',
    'School of Continuing Education': '持續教育學院',
    'School of Creative Arts': '創意藝術學院',
    'Sino-Forest Applied Research Centre for Pearl River Delta Environment': '珠江三角洲環境應用研究中心',
    'State Key Laboratory of Environmental and Biological Analysis': '環境與生物分析國家重點實驗室',
    'Statistics Research and Consultancy Centre': '統計研究及顧問中心',
    'The Beijing-Hong Kong-Singapore Joint Centre for Nonlinear and Complex Systems': '北京—香港—新加坡非線性與複雜系統聯合中心',
    'The EQUATOR China Centre': 'EQUATOR中國中心',
    'The Jao Tsung-I Academy of Sinology': '饒宗頤國學院',
    'Transdisciplinary Programmes': '跨學科課程',
    'Vincent V.C. Woo Chinese Medicine Clinical Research Institute': '胡永昌中醫臨床研究所',
    'Visualization Research Centre': '視覺化研究中心',
    'Wing Lung Bank International Inst for Business Development': '永隆銀行工商管理發展研究所',
    'Whole Person Development': '全人發展',
  },
  sc: {
    'Academy of Film': '电影学院',
    'Academy of Chinese, History, Religion and Philosophy': '中国语言、历史、宗教及哲学学院',
    'Academy of Global China Studies': '全球中国研究学院',
    'Academy of Geography, Sociology and International Studies': '地理、社会学及国际研究学院',
    'Academy of Language and Culture': '语言及文化学院',
    'Academy of Music': '音乐学院',
    'Academy of Visual Arts': '视觉艺术院',
    'Academy of Wellness and Human Development': '身心健康及全人发展学院',
    'Asian Energy Studies Centre': '亚洲能源研究中心',
    'Centre for Applied Ethics': '应用伦理学中心',
    'Centre for Business Analytics and the Digital Economy': '商业分析与数字经济中心',
    'Centre for China Urban and Regional Studies': '中国城市与区域研究中心',
    'Centre for Chinese Cultural Heritage': '中华文化遗产中心',
    'Centre for Chinese Herbal Medicine Drug Development Limited': '中药新药开发有限公司',
    'Centre for Corporate Governance and Financial Policy': '公司治理与金融政策研究中心',
    'Centre for Exercise Science and Medicine': '运动科学与医学中心',
    'Centre for Family Office Management': '家族办公室管理中心',
    'Centre for Health Informatics': '健康资讯学中心',
    'Centre for Health and Exercise Science Research': '健康与运动科学研究中心',
    'Centre for Human Resources Strategy and Development': '人力资源策略与发展中心',
    'Centre for Media and Communication Research': '媒体与传播研究中心',
    'Centre for Nonlinear Studies': '非线性研究中心',
    'Centre for Quantitative Systems Biology': '定量系统生物学中心',
    'Centre for Sino-Christian Studies': '中华基督宗教研究中心',
    'Centre for Sustainable Development Studies': '可持续发展研究中心',
    'Centre for Translation': '翻译中心',
    'Chinese Medicine - Clinical Division': '中医临床部',
    'Chinese Medicine - Division of Continuing and Professional Education': '中医持续及专业教育部',
    'Chinese Medicine - Teaching and Research Division': '中医教研部',
    'Chinese Medicine - Technology Development Division': '中医技术发展部',
    'Chinese Medicine Hospital': '中医医院',
    'Comparative Governance and Policy Research Centre': '比较治理与政策研究中心',
    'Croucher Institute for Environmental Sciences': '裘槎环境科学研究所',
    'David C Lam Institute for East-West Studies': '林思齐东西学术交流研究所',
    'Department of Accountancy, Economics and Finance': '会计、经济及金融学系',
    'Department of Biology': '生物系',
    'Department of Biomedical Sciences': '生物医学系',
    'Department of Chemistry': '化学系',
    'Department of Chinese Language and Literature': '中文系',
    'Department of Communication Studies': '传理学系',
    'Department of Computer Science': '计算机科学系',
    'Department of Education Studies': '教育学系',
    'Department of English Language and Literature': '英语语言文学系',
    'Department of Geography': '地理系',
    'Department of Government and International Studies': '政府与国际研究系',
    'Department of History': '历史系',
    'Department of Humanities and Creative Writing': '人文及创作系',
    'Department of Interactive Media': '互动媒体系',
    'Department of Journalism': '新闻系',
    'Department of Management': '管理学系',
    'Department of Management, Marketing and Information Systems': '管理、市场及资讯系统学系',
    'Department of Marketing': '市场学系',
    'Department of Mathematics': '数学系',
    'Department of Music': '音乐系',
    'Department of Physics': '物理系',
    'Department of Psychology': '心理学系',
    'Department of Religion and Philosophy': '宗教及哲学系',
    'Department of Social Work': '社会工作系',
    'Department of Sociology': '社会学系',
    'Department of Sport, Physical Education and Health': '体育、运动及健康学系',
    'Department of Translation, Interpreting and Intercultural Studies': '翻译、传译及跨文化研究系',
    'Division of Transdisciplinary Undergraduate Programmes': '跨学科本科课程部',
    'Digital Futures and Humanities': '数字未来与人文学',
    'Digital Humanities': '数码人文学',
    'Dr. Stephen Hui Research Centre for Physical Recreation and Wellness': '许士芬博士体育康乐与健康研究中心',
    'Entrepreneurship and Innovation Centre': '创业及创新中心',
    'European Studies Programme': '欧洲研究课程',
    'Faculty of Arts and Social Sciences': '文学院及社会科学院',
    'Faculty of Arts and Social Sciences (CHRP)': '文学院及社会科学院（中华相关课程）',
    'Faculty of Arts and Social Sciences (LAC)': '文学院及社会科学院（语言与文化课程）',
    'Faculty of Interdisciplinary Research': '跨学科研究学院',
    'Faculty of Science': '理学院',
    'Faculty of Social Sciences': '社会科学院',
    'General Education': '通识教育',
    'General Education Office': '通识教育处',
    'HKBU Motion Capture and Visualization Laboratory': '浸大动作捕捉与可视化实验室',
    'HKBU-RCEES Joint Institute of Environmental Sciences': '浸大—北师港浸大环境科学联合研究院',
    'Ho Sin Hang Campus': '善衡校园',
    'Hong Kong Baptist University': '香港浸会大学',
    'Hong Kong Traditional Chinese Medicine Phenome Research Centre': '香港中医药表型研究中心',
    'High Performance Cluster Computing Centre': '高性能集群计算中心',
    'Institute of Transdisciplinary Studies (Undergraduate)': '跨学科本科课程学院',
    'Institute of Advanced Materials': '先进材料研究所',
    'Institute of Computational and Theoretical Studies': '计算与理论研究所',
    'Institute of Precision Medicine and Innovative Drug Discovery': '精准医学与创新药物研发研究所',
    'Kai Tak Campus': '启德校园',
    'Language Centre': '语言中心',
    'Library': '图书馆',
    'Life Course Development Research Institute': '生命历程发展研究所',
    'Life Science Imaging Centre': '生命科学成像中心',
    'Modern History Research Centre': '近代史研究中心',
    'Mr. Simon Suen and Mrs. Mary Suen Sino-Humanitas Institute': '孙少文伉俪人文中国研究所',
    'Office of the Dean of Arts and Social Sciences': '文学及社会科学学院院长办公室',
    'Office of the Dean of Business': '工商管理学院院长办公室',
    'Office of the Dean of Chinese Medicine': '中医药学院院长办公室',
    'Office of the Dean of Communication': '传理学院院长办公室',
    'Office of the Dean of Creative Arts': '创意艺术学院院长办公室',
    'Office of the Dean of Science': '理学院院长办公室',
    'Office of the President and Vice-Chancellor': '校长兼副校监办公室',
    'Office of the Provost': '教务长办公室',
    'Office of the Vice-President (Administration) and Secretary': '副校长（行政）兼秘书长办公室',
    'Office of the Vice-President (Research and Development)': '副校长（研究及拓展）办公室',
    'Office of the Vice-President (Teaching and Learning)': '副校长（教与学）办公室',
    'Peking University-HKBU Joint Research Institute for Applied Mathematics': '北京大学—浸会大学应用数学联合研究所',
    'Research Centre for Herb Polysaccharides and Intestinal Immunology': '中药多糖与肠道免疫研究中心',
    'Research Centre for Standardization of Chinese Medicines': '中药标准化研究中心',
    'School of Business': '工商管理学院',
    'School of Chinese Medicine': '中医药学院',
    'School of Communication': '传理学院',
    'School of Continuing Education': '持续教育学院',
    'School of Creative Arts': '创意艺术学院',
    'Sino-Forest Applied Research Centre for Pearl River Delta Environment': '珠江三角洲环境应用研究中心',
    'State Key Laboratory of Environmental and Biological Analysis': '环境与生物分析国家重点实验室',
    'Statistics Research and Consultancy Centre': '统计研究及顾问中心',
    'The Beijing-Hong Kong-Singapore Joint Centre for Nonlinear and Complex Systems': '北京—香港—新加坡非线性与复杂系统联合中心',
    'The EQUATOR China Centre': 'EQUATOR中国中心',
    'The Jao Tsung-I Academy of Sinology': '饶宗颐国学院',
    'Transdisciplinary Programmes': '跨学科课程',
    'Vincent V.C. Woo Chinese Medicine Clinical Research Institute': '胡永昌中医临床研究所',
    'Visualization Research Centre': '视觉化研究中心',
    'Wing Lung Bank International Inst for Business Development': '永隆银行工商管理发展研究所',
    'Whole Person Development': '全人发展',
  },
  en: {
    'Academy of Film': 'Academy of Film',
    'Academy of Global China Studies': 'Academy of Global China Studies',
    'Academy of Music': 'Academy of Music',
    'Academy of Visual Arts': 'Academy of Visual Arts',
    'Department of Accountancy, Economics and Finance': 'Accountancy, Economics & Finance',
    'Department of Biology': 'Biology',
    'Department of Biomedical Sciences': 'Biomedical Sciences',
    'Department of Chemistry': 'Chemistry',
    'Department of Chinese Language and Literature': 'Chinese Language & Literature',
    'Department of Communication Studies': 'Communication Studies',
    'Department of Computer Science': 'Computer Science',
    'Department of Education Studies': 'Education Studies',
    'Department of English Language and Literature': 'English Language & Literature',
    'Department of Geography': 'Geography',
    'Department of Government and International Studies': 'Government & International Studies',
    'Department of History': 'History',
    'Department of Humanities and Creative Writing': 'Humanities & Creative Writing',
    'Department of Interactive Media': 'Interactive Media',
    'Department of Journalism': 'Journalism',
    'Department of Management': 'Management',
    'Department of Management, Marketing and Information Systems': 'Management, Marketing & IS',
    'Department of Marketing': 'Marketing',
    'Department of Mathematics': 'Mathematics',
    'Department of Music': 'Music',
    'Department of Physics': 'Physics',
    'Department of Psychology': 'Psychology',
    'Department of Religion and Philosophy': 'Religion & Philosophy',
    'Department of Social Work': 'Social Work',
    'Department of Sociology': 'Sociology',
    'Department of Sport, Physical Education and Health': 'Sport, PE & Health',
    'Department of Translation, Interpreting and Intercultural Studies': 'Translation & Intercultural Studies',
    'Digital Futures and Humanities': 'Digital Futures & Humanities',
    'Digital Humanities': 'Digital Humanities',
    'European Studies Programme': 'European Studies',
    'Faculty of Arts and Social Sciences': 'Arts & Social Sciences',
    'Faculty of Arts and Social Sciences (CHRP)': 'Arts & Social Sciences (CHRP)',
    'Faculty of Arts and Social Sciences (LAC)': 'Arts & Social Sciences (LAC)',
    'Faculty of Interdisciplinary Research': 'Interdisciplinary Research',
    'Faculty of Science': 'Faculty of Science',
    'Faculty of Social Sciences': 'Social Sciences',
    'General Education': 'General Education',
    'Ho Sin Hang Campus': 'Ho Sin Hang Campus',
    'Hong Kong Baptist University': 'HKBU',
    'Institute of Transdisciplinary Studies (Undergraduate)': 'Transdisciplinary Studies',
    'Kai Tak Campus': 'Kai Tak Campus',
    'Language Centre': 'Language Centre',
    'School of Business': 'School of Business',
    'School of Chinese Medicine': 'Chinese Medicine',
    'School of Communication': 'School of Communication',
    'School of Creative Arts': 'Creative Arts',
    'Transdisciplinary Programmes': 'Transdisciplinary Programmes',
    'Whole Person Development': 'Whole Person Development',
  },
};

export function getLocalizedRatingMetaLabel(value: string, lang: 'tc' | 'sc' | 'en'): string {
  const normalizedValue = value.trim();
  if (!normalizedValue) return '';

  if (normalizedValue.includes(';')) {
    const localizedParts: string[] = normalizedValue
      .split(';')
      .map((part) => getLocalizedRatingMetaLabel(part.trim(), lang))
      .filter(Boolean);
    return localizedParts.join(lang === 'en' ? '; ' : '；');
  }

  return getLocalizedHkbuCanteenLabel(normalizedValue, lang) ?? RATING_META_TRANSLATIONS[lang][normalizedValue] ?? normalizedValue;
}

export function getLocalizedRatingDepartment(item: RatingItem, lang: 'tc' | 'sc' | 'en') {
  return getLocalizedRatingMetaLabel(item.department ?? '', lang);
}

export function getLocalizedRatingLocation(item: RatingItem, lang: 'tc' | 'sc' | 'en') {
  if (!('location' in item)) return '';
  return getLocalizedRatingMetaLabel(item.location ?? '', lang);
}
