import type { RatingItem } from '../types';
import { getLocalizedHkbuCanteenLabel } from '../data/hkbuCanteenTranslations';

const RATING_META_TRANSLATIONS: Record<'tc' | 'sc' | 'en', Record<string, string>> = {
  tc: {
    'Academy of Film': '電影學院',
    'Academy of Global China Studies': '全球中國研究學院',
    'Academy of Music': '音樂學院',
    'Academy of Visual Arts': '視覺藝術院',
    'Department of Accountancy, Economics and Finance': '會計、經濟及金融學系',
    'Department of Biology': '生物系',
    'Department of Biomedical Sciences': '生物醫學系',
    'Department of Chemistry': '化學系',
    'Department of Chinese Language and Literature': '中文系',
    'Department of Communication Studies': '傳理學系',
    'Department of Computer Science': '計算機科學系',
    'Department of Education Studies': '教育學系',
    'Department of English Language and Literature': '英語語言文學系',
    'Department of Geography': '地理系',
    'Department of Government and International Studies': '政府與國際研究系',
    'Department of History': '歷史系',
    'Department of Humanities and Creative Writing': '人文及創作系',
    'Department of Interactive Media': '互動媒體系',
    'Department of Journalism': '新聞系',
    'Department of Management': '管理學系',
    'Department of Management, Marketing and Information Systems': '管理、市場及資訊系統學系',
    'Department of Marketing': '市場學系',
    'Department of Mathematics': '數學系',
    'Department of Music': '音樂系',
    'Department of Physics': '物理系',
    'Department of Psychology': '心理學系',
    'Department of Religion and Philosophy': '宗教及哲學系',
    'Department of Social Work': '社會工作系',
    'Department of Sociology': '社會學系',
    'Department of Sport, Physical Education and Health': '體育、運動及健康學系',
    'Department of Translation, Interpreting and Intercultural Studies': '翻譯、傳譯及跨文化研究系',
    'Digital Futures and Humanities': '數字未來與人文學',
    'Digital Humanities': '數碼人文學',
    'European Studies Programme': '歐洲研究課程',
    'Faculty of Arts and Social Sciences': '文學院及社會科學院',
    'Faculty of Arts and Social Sciences (CHRP)': '文學院及社會科學院（中華相關課程）',
    'Faculty of Arts and Social Sciences (LAC)': '文學院及社會科學院（語言與文化課程）',
    'Faculty of Interdisciplinary Research': '跨學科研究學院',
    'Faculty of Science': '理學院',
    'Faculty of Social Sciences': '社會科學院',
    'General Education': '通識教育',
    'Ho Sin Hang Campus': '善衡校園',
    'Hong Kong Baptist University': '香港浸會大學',
    'Institute of Transdisciplinary Studies (Undergraduate)': '跨學科本科課程學院',
    'Kai Tak Campus': '啟德校園',
    'Language Centre': '語言中心',
    'School of Business': '工商管理學院',
    'School of Chinese Medicine': '中醫藥學院',
    'School of Communication': '傳理學院',
    'School of Creative Arts': '創意藝術學院',
    'Transdisciplinary Programmes': '跨學科課程',
    'Whole Person Development': '全人發展',
  },
  sc: {
    'Academy of Film': '电影学院',
    'Academy of Global China Studies': '全球中国研究学院',
    'Academy of Music': '音乐学院',
    'Academy of Visual Arts': '视觉艺术院',
    'Department of Accountancy, Economics and Finance': '会计、经济及金融学系',
    'Department of Biology': '生物系',
    'Department of Biomedical Sciences': '生物医学系',
    'Department of Chemistry': '化学系',
    'Department of Chinese Language and Literature': '中文系',
    'Department of Communication Studies': '传理学系',
    'Department of Computer Science': '计算机科学系',
    'Department of Education Studies': '教育学系',
    'Department of English Language and Literature': '英语语言文学系',
    'Department of Geography': '地理系',
    'Department of Government and International Studies': '政府与国际研究系',
    'Department of History': '历史系',
    'Department of Humanities and Creative Writing': '人文及创作系',
    'Department of Interactive Media': '互动媒体系',
    'Department of Journalism': '新闻系',
    'Department of Management': '管理学系',
    'Department of Management, Marketing and Information Systems': '管理、市场及资讯系统学系',
    'Department of Marketing': '市场学系',
    'Department of Mathematics': '数学系',
    'Department of Music': '音乐系',
    'Department of Physics': '物理系',
    'Department of Psychology': '心理学系',
    'Department of Religion and Philosophy': '宗教及哲学系',
    'Department of Social Work': '社会工作系',
    'Department of Sociology': '社会学系',
    'Department of Sport, Physical Education and Health': '体育、运动及健康学系',
    'Department of Translation, Interpreting and Intercultural Studies': '翻译、传译及跨文化研究系',
    'Digital Futures and Humanities': '数字未来与人文学',
    'Digital Humanities': '数码人文学',
    'European Studies Programme': '欧洲研究课程',
    'Faculty of Arts and Social Sciences': '文学院及社会科学院',
    'Faculty of Arts and Social Sciences (CHRP)': '文学院及社会科学院（中华相关课程）',
    'Faculty of Arts and Social Sciences (LAC)': '文学院及社会科学院（语言与文化课程）',
    'Faculty of Interdisciplinary Research': '跨学科研究学院',
    'Faculty of Science': '理学院',
    'Faculty of Social Sciences': '社会科学院',
    'General Education': '通识教育',
    'Ho Sin Hang Campus': '善衡校园',
    'Hong Kong Baptist University': '香港浸会大学',
    'Institute of Transdisciplinary Studies (Undergraduate)': '跨学科本科课程学院',
    'Kai Tak Campus': '启德校园',
    'Language Centre': '语言中心',
    'School of Business': '工商管理学院',
    'School of Chinese Medicine': '中医药学院',
    'School of Communication': '传理学院',
    'School of Creative Arts': '创意艺术学院',
    'Transdisciplinary Programmes': '跨学科课程',
    'Whole Person Development': '全人发展',
  },
  en: {
    'Academy of Film': 'Academy of Film',
    'Academy of Global China Studies': 'Academy of Global China Studies',
    'Academy of Music': 'Academy of Music',
    'Academy of Visual Arts': 'Academy of Visual Arts',
    'Department of Accountancy, Economics and Finance': 'Accountancy, Economics & Finance',
    'Department of Biology': 'Biology',
    'Department of Biomedical Sciences': 'Biomedical Sciences',
    'Department of Chemistry': 'Chemistry',
    'Department of Chinese Language and Literature': 'Chinese Language & Literature',
    'Department of Communication Studies': 'Communication Studies',
    'Department of Computer Science': 'Computer Science',
    'Department of Education Studies': 'Education Studies',
    'Department of English Language and Literature': 'English Language & Literature',
    'Department of Geography': 'Geography',
    'Department of Government and International Studies': 'Government & International Studies',
    'Department of History': 'History',
    'Department of Humanities and Creative Writing': 'Humanities & Creative Writing',
    'Department of Interactive Media': 'Interactive Media',
    'Department of Journalism': 'Journalism',
    'Department of Management': 'Management',
    'Department of Management, Marketing and Information Systems': 'Management, Marketing & IS',
    'Department of Marketing': 'Marketing',
    'Department of Mathematics': 'Mathematics',
    'Department of Music': 'Music',
    'Department of Physics': 'Physics',
    'Department of Psychology': 'Psychology',
    'Department of Religion and Philosophy': 'Religion & Philosophy',
    'Department of Social Work': 'Social Work',
    'Department of Sociology': 'Sociology',
    'Department of Sport, Physical Education and Health': 'Sport, PE & Health',
    'Department of Translation, Interpreting and Intercultural Studies': 'Translation & Intercultural Studies',
    'Digital Futures and Humanities': 'Digital Futures & Humanities',
    'Digital Humanities': 'Digital Humanities',
    'European Studies Programme': 'European Studies',
    'Faculty of Arts and Social Sciences': 'Arts & Social Sciences',
    'Faculty of Arts and Social Sciences (CHRP)': 'Arts & Social Sciences (CHRP)',
    'Faculty of Arts and Social Sciences (LAC)': 'Arts & Social Sciences (LAC)',
    'Faculty of Interdisciplinary Research': 'Interdisciplinary Research',
    'Faculty of Science': 'Faculty of Science',
    'Faculty of Social Sciences': 'Social Sciences',
    'General Education': 'General Education',
    'Ho Sin Hang Campus': 'Ho Sin Hang Campus',
    'Hong Kong Baptist University': 'HKBU',
    'Institute of Transdisciplinary Studies (Undergraduate)': 'Transdisciplinary Studies',
    'Kai Tak Campus': 'Kai Tak Campus',
    'Language Centre': 'Language Centre',
    'School of Business': 'School of Business',
    'School of Chinese Medicine': 'Chinese Medicine',
    'School of Communication': 'School of Communication',
    'School of Creative Arts': 'Creative Arts',
    'Transdisciplinary Programmes': 'Transdisciplinary Programmes',
    'Whole Person Development': 'Whole Person Development',
  },
};

export function getLocalizedRatingMetaLabel(value: string, lang: 'tc' | 'sc' | 'en') {
  return getLocalizedHkbuCanteenLabel(value, lang) ?? RATING_META_TRANSLATIONS[lang][value] ?? value;
}

export function getLocalizedRatingDepartment(item: RatingItem, lang: 'tc' | 'sc' | 'en') {
  return getLocalizedRatingMetaLabel(item.department ?? '', lang);
}

export function getLocalizedRatingLocation(item: RatingItem, lang: 'tc' | 'sc' | 'en') {
  if (!('location' in item)) return '';
  return getLocalizedRatingMetaLabel(item.location ?? '', lang);
}
